### ISSUE TITLE
WordpressSuccessResponse when "rest_post_invalid_page_number"

### ISSUE THREAD

**Issue by matejmosko** [ArunPrakashG/wordpress_client#76]
When I call for json, I sometimes stumble on a problem when I get out of the pages range. I set page variable dynamically for paging capability in my app. However when I increment the page number for your requests to more than the maximum count, I end up with endless loading. 

When the response is rest_post_invalid_page_number, wordpress_client accepts this as success and tries to map the values into a list of posts. This results in this exception:

```
Unhandled Exception: type '_Map<String, dynamic>' is not a subtype of type 'Iterable<dynamic>' in type cast
E/flutter (20045): #0      IRequestExecutor.list.<anonymous closure> (package:wordpress_client/src/request_executor_base.dart:325:37)
E/flutter (20045): #1      WordpressRawResponse.map (package:wordpress_client/src/responses/wordpress_raw_response.dart:207:21)
E/flutter (20045): #2      IRequestExecutor.list (package:wordpress_client/src/request_executor_base.dart:322:24)
```
and the future client.posts.list(request) gets no response therefore it endlessly waits for the answer (and my loading is spinning endlessly as well)

Is there a way to get the Failure answer for the future even if the rawResponse is successfuly obtained, but it's invalid?

**Comment by ArunPrakashG** [comment]
Hi @matejmosko Could you please share a snippet to reproduce this?
I just tried recreating this and i was getting expected outcome in all of the cases.

```
{"code":"rest_post_invalid_page_number","message":"The page number requested is larger than the number of pages available.","data":{"status":400}}

Posts Count: {code: rest_post_invalid_page_number, message: The page number requested is larger than the number of pages available., data: {status: 400}}

Exited.

I am getting the error response and the script exits as expected.

Additionally, the status code is 400, this should not be mapped to a success response in any circumstances because it is fundamentally wrong. I can look into this further with few more inputs on how to reproduce this.
```

**Comment by ArunPrakashG** [comment]
@matejmosko Hey, any update here?

**Comment by matejmosko** [comment]
I am a bit busy now. I will have a look at it in a week. I am sorry

Dňa po 26. 8. 2024, 16:50 Arun Prakash ***@***.***>
napísal(a):

**Comment by ArunPrakashG** [comment]
Hey @matejmosko, it's not totally fine. I was just checked in. have a great day.

**Comment by ArunPrakashG** [comment]
Closing this as there is no activity.
